### PR TITLE
Adding Docker Image CI/CD Pipeline

### PR DESCRIPTION
**Pull request by Johnnybyzhang**
Title: **Adding Docker Image CI/CD Pipeline**

Description:

This pull request introduces a new GitHub Actions workflow that automatically builds and pushes Docker images to Docker Hub whenever there's a push or a pull request event on the main branch of the repository.

Here are the steps included in the workflow:

1. **Check out the repo**: This step uses the `actions/checkout` action to clone the repository's code onto the runner.
2. **Log in to Docker Hub**: This step uses the `docker/login-action` action to log into Docker Hub using the credentials stored in the repository's secrets.
3. **Extract metadata (tags, labels) for Docker**: This step uses the `docker/metadata-action` action to extract metadata about the Docker image.
4. **Build and push Docker image**: This step uses the `docker/build-push-action` action to build the Docker image using the Dockerfile in the backend directory, and then pushes the image to Docker Hub.

The workflow uses the `ubuntu-latest` GitHub-hosted runner and is triggered on `push` and `pull_request` events on the main branch.

Please review the code and provide feedback as needed.

### CODE REVIEW

**Comment by SichangHe** [comment]
This PR needs to be updated according to the recent Database change. Specifically, the dockerfile.

Please see the latest `backend/README.md`. Also, note that #15 forces a database reset.

**Comment by Johnnybyzhang** [comment]
This PR will be ready and has been tested working when #19 gets merged as the only failing part in checks is the docker build part

**Comment by SichangHe** [comment]
So, the plan is to merge #19 first, and then merge this one, right? @Johnnybyzhang

**Comment by Johnnybyzhang** [comment]
> So, the plan is to merge #19 first, and then merge this one, right? @Johnnybyzhang

That is correct, merging #19 first will allow GitHub to do the checks first before we finally merge this PR. As offline tests are still only theoretical.

**Comment by Johnnybyzhang** [comment]
Checks have failed due to the old Dockerfile, will update and reopen PR later

**Comment by SichangHe** [comment]
One thing I just noticed is that `seed.py` does not download the model whereas #19 deleted `prepare.sh` that does it. We still need a script to download the model.

**Comment by Johnnybyzhang** [comment]
> One thing I just noticed is that `seed.py` does not download the model whereas #19 deleted `prepare.sh` that does it. We still need a script to download the model.

Please check my `README` as the way to use models have been significantly altered in this docket image.

**Comment by SichangHe** [comment]
The README does not mention downloading the model, neither. There seems to be some misalignment in your expectation.

**Comment by Johnnybyzhang** [comment]
> The README does not mention downloading the model, neither. There seems to be some misalignment in your expectation.

Noted, will include more documentation in next PR

**Pull request closed without merging**
